### ISSUE TITLE
Error Code -9

### ISSUE THREAD

**Issue by Nightnightlight** [tdrussell/diffusion-pipe#9]
Getting a error code -9? I have all the model files / folders in the right location.
![-9](https://github.com/user-attachments/assets/21896780-d9b6-4cfa-ba17-2e4d7a09df9c)

**Comment by tdrussell** [comment]
I believe this means you are running out of memory (RAM, not VRAM) when loading the text encoder, and the process gets killed.

I took a look, the official HunyuanVideo code loads the text encoder in float32 precision then casts it to the configured dtype. I just pushed a patch that avoids this by directly loading it in the correct dtype (e.g. bfloat16). So it should use half the RAM while loading now. Pull the latest code and it might work now.

I'm assuming you probably have 32GB of RAM. Do note, the transformer model alone is 13b parameters, meaning 26GB in bfloat16. I think that the loading code loads it directly into fp8 though, if you have that configured? My point is though, there may be places where RAM usage is tight. The change I just pushed should fix the text encoder part but other parts might still OOM.

**Comment by Nightnightlight** [comment]
Still getting it, and yea 32GBs. Guess I'll have to upgrade to 64GB to run it.

**Comment by Bocchi-Chan2023** [comment]
on wsl right? try assign more rams modifying .wslconfig. or increasing swap.

**Comment by Bocchi-Chan2023** [comment]
It's works fine on my 32GB PC.

[wsl2]
localhostForwarding=true 
memory=24GB
swap=30GB
[experimental]
networkingMode=mirrored
dnsTunneling=true
autoProxy=true
sparseVhd=true
autoMemoryReclaim=gradual

**Comment by ShmuelRonen** [comment]
are they .wslconfig file on wsl?

**Comment by ShmuelRonen** [comment]
How I modifying .wslconfig ? windowsapp folder is protected
